
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@${DB_URL}:${PORT}/admin?maxMessageSize=52428800
      auto-startup: true
  jpa:
    show-sql: true