
management:
  endpoint:
    health:
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin?maxMessageSize=52428800
      auto-startup: true
  jpa:
    show-sql: true    