server:
  shutdown: graceful

management:
  endpoint:
    health:
      enable: true
      probes:
        enabled: true
      livenessState:
        enabled: true
      readinessState:
        enabled: true

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    mongodb:
      uri: mongodb://${USERNAME}:${PASSWORD}@${DB_URL}:${PORT}/admin?maxMessageSize=52428800
      auto-startup: true
  jpa:
    show-sql: true