

country:
  client:
    soap:
      package: com.springboot.project.web.services.model.gen
      url: http://localhost:8088/webservices-mock
#      url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL