spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin?maxMessageSize=52428800
      auto-startup: true
  jpa:
    show-sql: true