

country:
  client:
    soap:
#      package: com.springboot.project.web.services.model.gen
#      url: http://localhost:8088/webservices-mock
#      url: http://webservices.oorsprong.org/websamples.countryinfo/CountryInfoService.wso?WSDL
      hostname: webservices.oorsprong.org
      protocol: http
      port: 80
      api: websamples.countryinfo/websamples.countryinfo
#      api: websamples.countryinfo
