spring:
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true

cipher:
  encryption:
    aes:
      secret: adwasekewqmdrqwd
    sha256:
      salt: qweasdertdfg
    bcrypt:
      saltLength16: asdasdasdqwertyu
      cost: 10