spring:
  mandatory-file-encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
  datasource:
    url: jdbc:h2:file:./testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false

cipher:
  encryption:
    aes:
      secret: 0C2FB501A93B550B4550D685B4E1582888C18F65742C3D945A8014114FA268B9
    sha256:
      salt: 0C2FB501A93B550B4550D685B4E1582888C18F65742C3D945A8014114FA268B9
    bcrypt:
      saltLength16: 94A15E1F08550FFC
      cost: 10
    hmac:
      secret: 0C2FB501A93B550B4550D685B4E1582888C18F65742C3D945A8014114FA268B9